
## Eurostat

The comparison is based on annually summarised CL data and [Eurostat data](https://ec.europa.eu/eurostat/databrowser/view/tag00076/default/table?lang=en&category=t_fish), filtered by vessel flag country. Only years with corresponding CL data are shown, plus the most recent data year.

```{r eurostat-prep}
CLToT <- CL %>%
  filter(CLcatchCat == "Lan") %>%
  group_by(CLvesFlagCou, CLyear) %>%
  summarise(
    CLoffWeight = round(sum(CLoffWeight, na.rm = TRUE), digits = 0),
    CLsciWeight = round(sum(CLsciWeight, na.rm = TRUE), digits = 0),
    .groups = "drop"
  )

eurostatW <- eurostatW %>%
  mutate(
    values = round(values, digits = 0),
    time   = as.character(time)
  ) %>%
  # Append the most recent CL year even if Eurostat data is not yet available
  add_row(time = max(CL$CLyear),
          geo  = unique(CL$CLvesFlagCou))

eurostatComp <- left_join(eurostatW, CLToT,
                           by = c("time" = "CLyear", "geo" = "CLvesFlagCou")) %>%
  select(geo:CLsciWeight) %>%
  rename(CLvesFlagCou = geo, CLyear = time, EurostatWeight = values) %>%
  filter(!(is.na(CLoffWeight) & is.na(CLsciWeight)))
```

```{r eurostat-plot}
eurostatComp %>%
  pivot_longer(cols = c(EurostatWeight, CLoffWeight, CLsciWeight),
               names_to = "WeightSource", values_to = "Weight") %>%
  ggplot(aes(CLyear, Weight, fill = WeightSource)) +
  geom_bar(stat = "identity", position = "dodge") +
  ylab("Landed weight (t)") +
  theme_bw() +
  theme(text = element_text(size = 20),
        axis.text.x = element_text(angle = 90, hjust = 1))
```

```{r eurostat-table}
eurostatComp %>%
  datatable(
    extensions = "Buttons",
    options    = list(
      dom        = "Blfrtip",
      buttons    = c("copy", "csv", "excel"),
      lengthMenu = list(c(10, 25, 50, -1), c(10, 25, 50, "All"))
    )
  )
```
