
## Preliminary ICES catches

[Preliminary catch statistics](https://data.ices.dk/rec12/login.aspx) for the most recent data year provided to ICES are compared by species and area.

```{r prelcatch-prep}
prelC1 <- prelC %>%
  pivot_longer(cols      = c(Lan, BMS),
               names_to  = "CatchCategory",
               values_to = "PrelCWeight") %>%
  filter(Country %in% unique(CL$CLlanCou))

CL_agg <- CL %>%
  group_by(CLarea, CLyear, CLlanCou, CLcatchCat, CLspecCode, LatinName) %>%
  summarise(
    CLoffWeight = sum(CLoffWeight, na.rm = TRUE),
    CLsciWeight = sum(CLsciWeight, na.rm = TRUE),
    .groups = "drop"
  ) %>%
  filter(CLyear %in% unique(prelC1$Year))


prelC1 <- mutate(prelC1, AphiaID = as.character(AphiaID))

prelCatches <- left_join(
  prelC1, CL_agg,
  by = c(
    "Year"          = "CLyear",
    "Country"       = "CLlanCou",
    "AphiaID"       = "CLspecCode",
    "Species.Latin.Name" = "LatinName",
    "Area"          = "CLarea",
    "CatchCategory" = "CLcatchCat"
  )
) %>%
  pivot_longer(cols      = c(PrelCWeight, CLoffWeight, CLsciWeight),
               names_to  = "WeightSource",
               values_to = "Weight")
```

```{r prelcatch-plots-setup}
myplots <- lapply(
  sort(unique(prelCatches$Species.Latin.Name)),
  function(sp) {
    ggplot(filter(prelCatches, Species.Latin.Name == sp),
           aes(x = Area, y = Weight, fill = WeightSource)) +
      geom_bar(stat = "identity", position = "dodge") +
      facet_grid(~ CatchCategory) +
      RDBES_FILL +
      rdbes_theme() +
      labs(title = sp, fill = "Weight source")
  }
)
names(myplots) <- sort(unique(prelCatches$Species.Latin.Name))
```

```{r prelcatch-plots-render, results='asis'}
for (sp in names(myplots)) {
  catHeader(sp, 3)
  print(myplots[[sp]])
}
```
