---
# date: "`r format(Sys.time(), '%d %B, %Y')`"
output: 
  html_document:
    toc: true
    toc_depth: 4
    number_sections: true
    toc_float: true
params:
  RDBESfile: RDBESfile
  eurostat: eurostat
  prelcatchstat: prelcatchstat
  prelcatchFile: prelcatchFile
  fleetRegister: fleetRegister
  fleetRegisterFile: fleetRegisterFile
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE, fig.height = 10, fig.width = 14)
options(scipen=999)
```

```{r}
# Packages 
# Installs missing packages automatically 
list.of.packages <- c("icesVocab", "tidyverse", "eurostat", "DT", "rnaturalearth", "rnaturalearthdata", "sf", "mapplots", "kableExtra", "ggpubr", "remotes")
new.packages <- list.of.packages[!(list.of.packages %in% installed.packages()[,"Package"])]
if(length(new.packages)) install.packages(new.packages)

if(!"RDBEScore" %in% installed.packages()[,"Package"]){
  remotes::install_github("ices-tools-dev/RDBEScore", build_vignettes = TRUE)
}

# Loads packages 
library(icesVocab)
library(tidyverse, quietly = TRUE)
library(eurostat)
library(DT)
library(rnaturalearth)
library(rnaturalearthdata)
library(sf)
library(mapplots)
library(kableExtra)
library(ggpubr)
library(RDBEScore)

```


```{r}
# Functions 
# TODO add catHeader to script and load them all at once 
# source("../Functions/read.rdbes.R")
source("../Functions/rdbes.fc.R")
source("../Functions/read.prelC.R")
source("../Functions/read.fleet.R")
catHeader <- function(text = "", level = 3) {
    cat(paste0("\n\n", 
               paste(rep("#", level), collapse = ""), 
               " ", text, "\n"))
}

```

```{r}
# Read auxiliary files 
# RCG areas 
url <- "https://raw.githubusercontent.com/ices-eg/RCGs/master/Metiers/Reference_lists/AreaRegionLookup.csv"
Area <- read.csv(url, header = TRUE)
### Fix the extra space in rcg region code
Area <- mutate(Area, Code = ifelse(Code %in% "NSEA                                    " , "NSEA",
                             ifelse(Code %in% "NAtl                                      ", "NAtl", Code))) %>%
  select(AreaCode, Code)

#Read the rectangle list from the repository 
url <- "https://github.com/ices-tools-dev/RDBES/raw/master/QC-scripts/RectangleList/ICESRectAreas.csv"
ICESrect <- read.csv(url, header = TRUE)

```



```{r}
# Read RDBES CL, CE files 
df <- createRDBESDataObject(input = params$RDBESfile) 
# For now use this 
# df <- read.rdbes(params$RDBESfile)
CL <- as.data.frame(df[["CL"]])
CE <- as.data.frame(df[["CE"]])

# Change class of some fields for plotting 
CL <- rdbes.fc(CL)
# Quick fix of CE col names - inconsistency between CE-CL lowercase and upper case for some fields 
names(CE)[names(CE) == 'CEMonth'] <- 'CEmonth'
names(CE)[names(CE) == 'CEArea'] <- 'CEarea'
CE <- rdbes.fc(CE)
```

```{r}
clY <- sort(unique(CL$CLyear))
ceY <- sort(unique(CE$CEyear))
# TODO add consistency checks between CL and CE and add warning for the comparison of both if there are
# no matching years 

if(all(clY == ceY) & length(unique(clY)) > 1){
  titleR <- paste("National quality report for years", paste(clY, collapse = ", "))
}else{
  titleR <- paste("National quality report for year ", clY)
}
```

---
title: `r titleR`
---



```{r}
# Processing 
# Get species scientific name from aphiaID
ScName <- getCodeList("SpecWorms") %>%
  select(Description, Key) %>%
  rename(LatinName = Description)
CL <- left_join(CL, ScName, by = c("CLspecCode" = "Key")) 
```

```{r}

# CL$CLcatchCategory <- "RegDis"
# CL$CLregDisCategory <- "Deminimis"

```

# Summary 

Add text with a brief summary describing what the document's purpose is etc. 

```{r}
# Number of records 
CLr <- CL %>%
  group_by(CLyear) %>%
  count() %>%
  mutate(Dataset = "CL") %>%
  rename(Year = CLyear)
CEr <- CE %>%
  group_by(CEyear) %>%
  count() %>%
  mutate(Dataset = "CE") %>%
  rename(Year = CEyear)
tabN <- rbind(CLr, CEr) %>%
  spread(Year, n) 

tabN %>%
  datatable(caption = "Number of records in the CL and CE tables by year", options = list(dom = 't'))
```


```{r}
# Numbers of metier lvl 6 
CLm <- CL %>%
  group_by(CLyear) %>%
  summarise(Nmet = length(unique(CLmetier6))) %>%
  mutate(Dataset = "CL") %>%
  rename(Year = CLyear)
CEm <- CE %>%
  group_by(CEyear) %>%
  summarise(Nmet = length(unique(CEmetier6))) %>%
  mutate(Dataset = "CE") %>%
  rename(Year = CEyear)
tabN <- rbind(CLm, CEm) %>%
  spread(Year, Nmet) 

tabN %>%
  datatable(caption = "Number of unique metiers level 6 in the CL and CE tables by year", options = list(dom = 't'))

```

```{r}
# Number of unique vessels by year 

CLv <- select(CL, CLyear, CLencrypVesIds) %>%
  distinct() %>%
  separate_rows(CLencrypVesIds, convert = TRUE) %>%
  distinct() %>%
  group_by(CLyear) %>%
  summarise(NumberOfUniqueVessels = length(unique(CLencrypVesIds))) %>%
  mutate(Dataset = "CL") %>%
  rename(Year = CLyear)
CEv <- select(CE, CEyear, CEencrypVesIds) %>%
  distinct() %>%
  separate_rows(CEencrypVesIds, convert = TRUE) %>%
  distinct()%>%
  group_by(CEyear) %>%
  summarise(NumberOfUniqueVessels = length(unique(CEencrypVesIds)))%>%
  mutate(Dataset = "CE") %>%
  rename(Year = CEyear)

tabV <- rbind(CLv, CEv)%>%
  spread(Year, NumberOfUniqueVessels) 
tabV %>%
  datatable(caption = "Number of unique vessels in the CL and CE tables by year", options = list(dom = 't'))
```


```{r}
# Number of species
CLsp <- CL %>%
  group_by(CLyear) %>%
  summarise(NumberOfSpecies = length(unique(CLspecCode)))

CLsp %>%
  datatable(caption = "Number of species by year in the CL table" , colnames = c("Year" = 1), rownames = FALSE, options = list(dom = 't'))

```


```{r}
# Run next chunk? 
doNextChunk <- any(c(params$eurostat, params$prelcatchstat, params$fleetRegister))
```


```{r, results='asis', eval = doNextChunk}
cat("# Comparison with auxiliary data sources")
```



```{r, eval = params$eurostat}
# Auxiliary information for comparisons 
# 1. Eurostat data - weight 
eurostatW <- get_eurostat("tag00076", time_format = "num", filters = list(geo = unique(CL$CLlanCou)), stringsAsFactors = TRUE) # tag corresponds to catches in all fishing regions by country
# https://ec.europa.eu/eurostat/databrowser/view/tag00076/default/table?lang=en&category=t_fish

# 2. Eurostat data - number of vessels 
# eurostatV <- get_eurostat("tag00076", time_format = "num", filters = list(geo = unique(CL$CLlandingCountry)), stringsAsFactors = TRUE)

```

```{r,  child = '01_Eurostat.Rmd', eval = params$eurostat}

```

```{r, eval = params$prelcatchstat}
# 2. ICES preliminary catches
prelC <- read.prelC(params$prelcatchFile)
```


```{r,  child = '02_PreliminaryCatches.Rmd', eval = params$prelcatchstat}

```


```{r, eval = params$fleetRegister}
# 3. Fleet register 
fleet <- read.fleet(params$fleetRegisterFile)
```

```{r, child = '03_FleetRegister.Rmd', eval = params$fleetRegister}

```


```{r, child = '04_CL_Multiannual.Rmd'}

```


```{r, child = '05_CE_Multiannual.Rmd'}

```


```{r, child = '07_Spatial_checks.Rmd'}

```

